"""
Django settings for jobmatcher project.

Generated by 'django-admin startproject' using Django 6.0.1.
"""

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY
SECRET_KEY = "django-insecure-$ztrp!hml-gx4+tt+_cj%^y!wcbw#-az(o_2wnmfd=)i_hioa&"

DEBUG = True

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "testserver",
]


# APPLICATIONS

INSTALLED_APPS = [
    "django.contrib.staticfiles",

    "rest_framework",
    "corsheaders",
    "matcher",
]


# MIDDLEWARE

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "jobmatcher.urls"


# TEMPLATES

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
            ],
        },
    },
]


WSGI_APPLICATION = "jobmatcher.wsgi.application"


# DATABASE (MongoDB)

MONGODB_NAME = os.getenv("MONGODB_NAME", "intelligent_job_matcher")
MONGODB_HOST = os.getenv("MONGODB_HOST", "127.0.0.1")
MONGODB_PORT = int(os.getenv("MONGODB_PORT", "27017"))
MONGODB_USER = os.getenv("MONGODB_USER", "")
MONGODB_PASSWORD = os.getenv("MONGODB_PASSWORD", "")
MONGODB_AUTH_SOURCE = os.getenv("MONGODB_AUTH_SOURCE", "admin")

DATABASES = {
    "default": {
        "ENGINE": "django_mongodb_backend",
        "NAME": MONGODB_NAME,
        "HOST": MONGODB_HOST,
        "PORT": MONGODB_PORT,
        "USER": MONGODB_USER,
        "PASSWORD": MONGODB_PASSWORD,
        "OPTIONS": {
            "authSource": MONGODB_AUTH_SOURCE,
        },
    }
}


# PASSWORD VALIDATION

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# INTERNATIONALIZATION

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# STATIC FILES

STATIC_URL = "static/"


# CORS (Allow React Frontend)

CORS_ALLOW_ALL_ORIGINS = True


# REST FRAMEWORK + JWT AUTHENTICATION

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "matcher.authentication.MongoJWTAuthentication",
    ),
    "UNAUTHENTICATED_USER": None,
}

# Keep default PK type Mongo-compatible for any future Django models.
DEFAULT_AUTO_FIELD = "django_mongodb_backend.fields.ObjectIdAutoField"